stages:
  - deploy-dev

deploy-dev:
  image: alpine
  stage: deploy-dev
  script:
    - apk add git
    - git clone https://github.com/HyagoHirai/Teste.git
    - git branch
    - git checkout $CI_COMMIT_REF_NAME
    - echo "$CI_COMMIT_REF_NAME"
